name: project
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.6
  - pytorch==1.3.0
  - torchvision
  - scikit-learn
  - numpy
  - scipy
  - pandas
  - matplotlib==3.1.0
  - pytest
  - gensim
  - spacy
  - transformers
  - nltk
  - pip
  - pip:
    - delayed-assert
